import 'package:flutter/material.dart';

class Document {
  final String mon;
  final String lop;
  final String tailieu;
  final String video;
  final String content;
  final String thionline;
  final String url;
  final int sentenceCont;

  Document(
      {this.mon,
      this.lop,
      this.tailieu,
      this.video,
      this.thionline,
      this.content,
      this.sentenceCont,
      this.url});
}

List<Document> document = [
  Document(
    mon: 'toán',
    lop: '11',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '12',
    tailieu: 'Các phép toán vector trong không gian',
    video: 'Phản xạ toàn phần',
    thionline: 'Trác nghiệm toán 12',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '12',
    tailieu: 'Giải toán 12: Ôn tập về giải toán',
    video: 'Tập hợp và các phép toán trên tập hợp',
    thionline: 'Trác nghiệm toán 3',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '12',
    tailieu: 'Các bài toán liên quan đến tiệm cận của hàm số',
    video: 'Lý thuyết: Phương pháp quy nạp toán học',
    thionline: 'Cách giải bài toán đếm số phương án',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '11',
    tailieu: 'Giải toán 11',
    video: 'Giải sách giáo khoa các phép toán trên tập hợp',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '6',
    tailieu: 'Bài 49 trang 24 SGK Toán 6 tập 1',
    video: 'Giải SGK- bài 5- Phép cộng và phép nhân',
    thionline: 'Trác nghiệm toán 6 baì 9 (có đáp án) ',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '6',
    tailieu: 'Bài 52 trang 25 SGK Toán 6 tập 1',
    video: 'Ôn tập chương 1 hình học',
    thionline: 'Trác nghiệm toán 6 baì 12 (có đáp án)',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '5',
    tailieu: 'Giải bài 2 trang 185 SGK Toán 5',
    video: 'Giải SGK- bài 5- Phép cộng và phép nhân',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '5',
    tailieu: 'Giải bài 4 trang 178 sgk Toán 5',
    video: 'Toán học 5- Số thập phân bằng nhau',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '8',
    tailieu: 'Giải toán 8: Bài 5 Gải bài toán bằng...',
    video: 'Bài toán dân số',
    thionline: 'Trác nghiệm bài toán dân số có đáp án',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '8',
    tailieu: 'Bài 60 trang 99 toán 8 tập 1',
    video: 'Giải sgk- Định luận bảo toàn khối lượng',
    thionline: 'Bài tập 8: Phân tích đại số có đáp án',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '7',
    tailieu: 'Bài 12 trang 12 Toán 7 tập 1',
    video: 'Giải SGK bài 9 an toàn khi sử dụng điện',
    thionline: 'Trác nghiệm toán 7 bài 5: Hàm số',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '7',
    tailieu: 'Bài 17 trang 13 toán 7 ',
    video: 'Giải SGK- bài 2 một số bài toán về tỷ lệ thuật',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '10',
    tailieu: 'Các vecto chỉ phương của đường thẳng',
    video: 'Bài giảng - các phép toán tổng hợp',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '10',
    tailieu: 'Viết phương trình tổng quát của phương trình đường thẳng',
    video: 'Bài giảng: Khái niệm vector và các phép toán vector',
    thionline: 'Trác nghiệm toán 10 ( có đáp án)',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '11',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '10',
    tailieu: 'Các công thức vè phương  trình đường thẳng',
    video: 'Bài giảng các phép toán về tập hợp',
    thionline: 'Trác nghiệm chương 3 có đáp án',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '8',
    tailieu: 'Bài 60 trang 99 toán 8 tập 1',
    video: 'Giải sgk- Định luận bảo toàn khối lượng',
    thionline: 'Bài tập 8: Phân tích đại số có đáp án',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '11',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '11',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '12',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '11',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '11',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '5',
    tailieu: 'Giải bài 2 trang 185 SGK Toán 5',
    video: 'Giải SGK- bài 5- Phép cộng và phép nhân',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '6',
    tailieu: 'Bài 49 trang 24 SGK Toán 6 tập 1',
    video: 'Giải SGK- bài 5- Phép cộng và phép nhân',
    thionline: 'Trác nghiệm toán 6 baì 9 (có đáp án) ',
    content: 'nôi dung',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '7',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
  Document(
    mon: 'toán',
    lop: '9',
    tailieu: 'Phương pháp quy nạp toán học',
    video: 'Giải SGK- bài 5- Phương pháp giải một số bài toán về mạch',
    thionline: 'Bài 29 trang 19 SGK toán lơp 1 tập 2',
    content: '',
    sentenceCont: 10,
    url: '',
  ),
];
